module.exports = {
  siteMetadata: {
    title: `Masaya Shida`,
    description: `Web & graphics designer based in Phnom Penh, Cambodia.`,
    author: `Masaya Shinoda`,
    siteUrl: `https://masayashida.xyz`,
    keywords: [
      `Masaya Shida`,
      `masayashinoda`,
      `Masaya`,
      `Shida`,
      `MasayaShida`,
      `masayashida`,
      `masaya shida`,
      `Masaya Portfolio`,
      `Masaya Design`,
      `Masaya Photography`,
      `masayashinoda.github.io`,
      `masayashida.xyz`,
      `Web design`,
      `Web design in phnom penh`,
      `Web development in phnom penh`,
      `Web dev`,
      `front-end web development`,
      `frontend web development cambodia`,
      `frontend web developer cambodia`,
      `web designer cambodia`,
      `web designer phnom penh`,
      `freelance web developer`,
      `freelance web developer phnom penh`,
      `freelance web developer in cambodia`,
      `freelance web designer`,
      `freelance web designer phnom penh`,
      `freelance web developer in cambodia`,
      `freelance web designer in cambodia`,
      `freelance graphics designer in cambodia`,
      `freelance photographer`,
      `freelance photographer phnom penh`,
      `freelance photographer in phnom penh`,
      `freelance graphic designer phnom penh`,
      `graphic designer in phnom penh`,
      `graphic design phnom penh`,
      `graphic designer cambodia`,
      `graphic designer in cambodia`,
    ],
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Masaya Portfolio`,
        short_name: `Masaya Portfolio`,
        start_url: `/`,
        background_color: `#183152`,
        theme_color: `#244979`,
        display: `Masaya Shida`,
        icon: `src/images/logo.png`, // This path is relative to the root of the site.
      },
    },
    `gatsby-plugin-advanced-sitemap`,
    `gatsby-plugin-fontawesome-css`
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
